spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionstockspringboot
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # spécification SGBD qu'on va utiliser
  jpa:
    database: MYSQL
    show-sql: false
    # Hibernate DDL auto(create, create-drop ou update)
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ejb:
          interceptor: com.med.gestiondestock.interceptor.Interceptor
  port: 8080

#  mvc:
#    pathmatch:
#      matching-strategy:
#        server: ant_path_matcher

flickr:
  apiKey: 268b10df72138c28d9a1078a51aebfc5
  apiSecret: c85d78c90d59e885
  appKey: 72157720858467299-22b8ee0a8988ffd1
  appSecret: 836a2c7b6bd6b592

springdoc:
  default-produces-media-type: application/json